ingress: "https://arbeidsplassen.intern.dev.nav.no/min-side"
arbeidsplassen_url: "https://arbeidsplassen.intern.dev.nav.no"
loglevel: "debug"
namespace: "teampam"
pam_aduser_audience: "dev-gcp:teampam:pam-aduser"
pam_aduser_url: "http://pam-aduser"
